spring.application.name=app-items

server.port=${PORT:8080}

spring.datasource.url=${DATASOURCE_URL:jdbc:postgresql://localhost:5432/app-items}
spring.datasource.username=${DATASOURCE_USER:postgres}
spring.datasource.password=${DATASOURCE_PASSWORD:ca2162sa}

frontend.url=${FRONTEND_URL:http://localhost:3000}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

